import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import '@/app/ui/global.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <h1 className="text-blue-500">I'm blue!</h1>
      
      </body>
    </html>
  );
}
